### ISSUE TITLE
Firewall rules are not necessarily applied after reboot caused by a crash

### ISSUE THREAD

**Issue by ohrensessel** [ffnord/ffnord-puppet-gateway#101]
This is because iptables-persistent has to be called manually after build-firewall has been executed to save the new rules. Maybe it would be helpful if build-firewall would call iptables-persistent after each run to be sure the new rules are saved.

**Comment by sargon** [comment]
Yes, storing the firewall settings after a build-firewall run is a good idea.

**Comment by ohrensessel** [comment]
closed as resolved by #102
