### ISSUE TITLE
Adapt for pyddhcpd (when stable)

### ISSUE THREAD

**Issue by rubo77** [ffnord/ffnord-puppet-gateway#121]
There is needed an option to support https://github.com/tcatm/pyddhcpd

**Comment by ohrensessel** [comment]
for what reason? as there is not yet an implementation, that can run on
nodes as well, I don't see any use case for having pyddhcpd on a gateway.

if you, nevertheless, feel that there is a need for this feature, please
implement it and I will happily merge it.

2015-06-18 17:42 GMT+02:00 Ruben Barkow <notifications@github.com>:

**Comment by rubo77** [comment]
Ok, so once it is stable, we need that option, until then this will stay just an open issue
