### ISSUE TITLE
add better understandeable explanation to ffnord-update.common

### ISSUE THREAD

**Issue by rubo77** [ffnord/ffnord-puppet-gateway#134]
Can someone please add a better explanation in the head of https://github.com/ffnord/ffnord-puppet-gateway/blob/master/files/usr/local/include/ffnord-update.common ?

**Comment by sargon** [comment]
I fear that is my broken english.... will do soon, after the open source and linux days in kiel.

**Comment by rubo77** [comment]
Still not clear

**Comment by rubo77** [comment]
ich habs mal versucht, bitte mal anschauen: https://github.com/ffnord/ffnord-puppet-gateway/blob/master/files/usr/local/include/ffnord-update.common
