### ISSUE TITLE
maintenance enhanceent

### ISSUE THREAD

**Issue by rubo77** [ffnord/ffnord-puppet-gateway#140]
pinneberg has this precedure:

>batctl gw off
>1 Minute warten
>DHCP Server deaktivieren /etc/init.d/isc-dhcp-server stop
>10 Minuten warten, damit die Clients eine IP-Adresse von einem anderen Gateway bekommen haben
>fastd beenden /etc/init.d/fastd stop

maybe we shoud adapt this too?

**Comment by sargon** [comment]
Like discussed before, we are not going to implement such shutdown procedure in the maintenance script itself....
