### ISSUE TITLE
CMPv6 filter in firewall einpflanzen

### ISSUE THREAD

**Issue by rubo77** [ffnord/ffnord-puppet-gateway#141]
Es gibt ein Problem, wodurch man das ganze Netz lahm legen kann, durch duplizierte MAC Adressen. Und dadurch irgendwie ausgeloesste ICMPv6 Neigh=
bor Sozialisation Floods.
Man k=C3=B6nnte in die Firewall der Gateways mal das entsprechende IPv6 I=
CMPv6 filter rfc einpflegen.
Da werden, wenn ich mich richtig erinnere, auch neighbor sozialisation et=
c. rate limit eingef=C3=BChrt,
und das so ohne, dass man sich dabei IPv6 kaputt macht.

**Comment by ohrensessel** [comment]
sorry aber hast du getrunken?

**Comment by sargon** [comment]
lol ... 
I think we close this one and start over cleanly.

**Comment by rubo77** [comment]
hehe, aufm handy war das nicht so einfach zu erledigen, aber ich wollte das schon mal festhalten ;)

Das war auf jeden fall ja fatal vorgestern, dass man durch so eine fehlconfiguration von irgendeinem client im Netz die gesamte stadt lahmlegt. denke das ist wichtig, dass so etwas abgefangen wird.

Vielleicht kann @sargon das mal verständlich als issue formulieren
