### ISSUE TITLE
 puppet parser validate / puppet-lint

### ISSUE THREAD

**Issue by pinguinpfleger** [ffnord/ffnord-puppet-gateway#144]
Ich werfe mal [puppet parser validate](https://docs.puppetlabs.com/references/3.6.latest/man/parser.html#ACTIONS) sowie [puppet-lint](http://puppet-lint.com) und ein kleines Bash-Script zum Validieren in die Runde.

```bash
#!/bin/bash

if [ $# -lt 1 ];then
  echo "$0 .pp-files"
  exit 1
fi

for manifest in $*;do
  echo "Validiere $manifest"
  puppet parser validate $manifest
  puppet-lint --no-80chars-check --with-filename $manifest
done
```

**Comment by MTRNord** [comment]
Wie wäre es in dem Zug dann auch ein travis "build" check anzulegen?

**Comment by pinguinpfleger** [comment]
hört sich so an als wäre es was tolles :)

**Comment by MTRNord** [comment]
@pinguinpfleger was muss man installieren um die commands zu nutzen dann mach ich eine pull request für den travis mist auf. den dann die amins einrichten dürfen ;)

**Comment by pinguinpfleger** [comment]
puppet und puppet-lint

**Comment by MTRNord** [comment]
@pinguinpfleger gehen die per apt-get zu installieren? :)

**Comment by pinguinpfleger** [comment]
selbstverständlich :)
Du kannst mit `apt-cache search <paketname>` aber auch nachsehen ob es in deiner Debian Version als Paket vorhanden ist.

**Comment by MTRNord** [comment]
@pinguinpfleger hatte gerade kein debian oider ubuntu hier. Muss gerade leider Windoof nutzen

**Comment by MTRNord** [comment]
@pinguinpfleger ps: was muss ich beim start des script beachten? :)
