### ISSUE TITLE
vcsrepo modul doesn't work any more

### ISSUE THREAD

**Issue by rubo77** [ffnord/ffnord-puppet-gateway#163]
When I try run puppet, I get

    Could not autoload vcsrepo: Could not autoload /etc/puppet/modules/vcsrepo/lib/puppet/provider/vcsrepo/git.rb: undefined method `has_command' for Puppet::Type::Vcsrepo::ProviderGit:Class at /etc/puppet/modules/ffnord/manifests/alfred.pp:9

on that tline there is definded the alfred repo:
```

vcsrepo { '/opt/alfred': 
    ensure => present, 
    provider => git, 
    revision => "6ffa009183cf5a223bf2198f7711b143b1e80109", 
    source => "https://git.open-mesh.org/alfred.git"; 
  } 

```

**Comment by sargon** [comment]
We had that problem with other modules, too. They use new puppet features which are not available in the debian puppet versions, so you have to replace the installed module with an earlier version.
