### ISSUE TITLE
http://debian.draic.info/ repo for Debian 32bit is gone

### ISSUE THREAD

**Issue by fsteinel** [ffnord/ffnord-puppet-gateway#165]
notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: Failed to fetch http://debian.draic.info/dists/wheezy/main/binary-i386/Packages  404  Not Found [IP: 95.143.172.184 80]

**Comment by rubo77** [comment]
when do you get this? yesterday it worked fine

**Comment by rubo77** [comment]
Who needs 32bit?

**Comment by rubo77** [comment]
http://debian.draic.info/dists/wheezy/main/binary-amd64/Packages works

**Comment by rubo77** [comment]
Now the repo is completely gone. I have a copy at https://github.com/rubo77/alfred-repository
