### ISSUE TITLE
IPv6 - vpn7.ffki schickt RAs, die zu einer default-Route führen.

### ISSUE THREAD

**Issue by fsteinel** [ffnord/ffnord-puppet-gateway#166]
Im fixup Script zum puppet wird die [radvd.conf](https://github.com/ffnord/ffnord-puppet-gateway/blob/ea2afc8fefcd07d13302ec5632bf76900fb30e97/manifests/bird6.pp) durch https://github.com/freifunk-kiel/ffki-puppet-gateway-install/blob/e09e7fc8779b8dc11a3e805873c26dc7c25a6dc9/post-puppet.sh#L31 ersetzt.
Damit soll das verschicken der ```RAs, die zu einer default-Route führen``` unterbunden werden.

- [x] Ist #160 bereits eine Umsetzung als puppet Script davon?
- [ ] Weitere Informationen von einem Client System sammeln

**Comment by fsteinel** [comment]
@wklaebe kannst du mir ```ip address show``` einfügen? Vorher nachher oder als Beschreibung?
@Tarnatos hast du dazu noch Infos?

**Comment by Tarnatos** [comment]
Keine Ahnung hat @rubo77 geschrieben. Dort werden aber wohl mehrere Dinge verändert...

**Comment by rubo77** [comment]
fixed
