### ISSUE TITLE
datensparsamkeit: patch isc-dhcp-server to clean dhcpd.leases

### ISSUE THREAD

**Issue by fsteinel** [ffnord/ffnord-puppet-gateway#170]
isc-dhcp-server cleans the dhcpd.leases every 3600 seconds...
This is **not** based on the lease time and is compiled in.
[Source](https://serverfault.com/questions/625619/isc-dhcp-leases-file-never-cleaned/625642#625642) and [Source ML](https://lists.isc.org/pipermail/dhcp-users/2010-September/012274.html)
server/db.c:
```c
#define LEASE_REWRITE_PERIOD 3600
```

Workaround
----------------
[Cleanup leases perl script](https://lists.isc.org/pipermail/dhcp-users/2006-September/001845.html)

**Comment by rubo77** [comment]
duplicate: #179
