### ISSUE TITLE
build-firewall: port to jessie

### ISSUE THREAD

**Issue by fsteinel** [ffnord/ffnord-puppet-gateway#174]
port build-firewall to jessie
service iptables-persistent got renamed to netfilter-persistent
adapt via puppet script and use puppet variable iptablespersistentservice

**Comment by rubo77** [comment]
@sventhomsen already did a lot of efford iin migrating to jessie:

https://github.com/sventhomsen/ffnord-puppet-gateway/commit/471b468c8a78ecd1f2591170a0cd431d14336b3d

**Comment by fsteinel** [comment]
there are at least 3 forks to port to jessie and no tracking bug/issue.
Makes it difficult to coordinate...
I suspended my work on the jessie branch (reason: private) and want to resume.

@sventhomsen @rubo77 @sargon @MTRNord:
Is there anything that needs to be done?

**Comment by rubo77** [comment]
fixed
