### ISSUE TITLE
Fastd logging multi-community support

### ISSUE THREAD

**Issue by sargon** [ffnord/ffnord-puppet-gateway#18]
Fastd logging should be optional configurable and one log file per community.

**Comment by ohrensessel** [comment]
at least one log file per community is introduced with #111 

regarding the log level (or logging in general): I think it is fine to have a preconfigured log level that is suitable for production usage. if something has to be debugged, loglevel can be changed locally.

**Comment by sargon** [comment]
Okay that one is merged. I think this issue can be closed for now.
