### ISSUE TITLE
Add script to test gateway status when finished

### ISSUE THREAD

**Issue by rubo77** [ffnord/ffnord-puppet-gateway#99]
There should be added a script, that shows a status of the gateway when you are logged in via SSH, with:
- all services that should run
- an analysis of all configurations 
- if everything is set up correctly.
- ...

This could look like this:

```
#!/bin/bash
set -x

maintenance status
batctl-ffki gw
service openvpn status
ping -I tun-anonvpn 8.8.8.8
batctl-ffki gw
service --status-all 2>&1 | egrep '(bird6|openvpn|fastd|alfred|bat)'
```

**Comment by ohrensessel** [comment]
generally a very good idea. might be helpful to check everything while connected via ssh.
however, we have to avoid duplicated code with the monitoring solutions here I would say.

would be nice if you provide a pull requests we then can review and merge.

**Comment by rubo77** [comment]
Where would this kind of script be in the correct place? In usr local bin?
https://github.com/ffnord/ffnord-puppet-gateway/tree/master/files/usr/local/bin

I need some more tips what tests should be included and where I should look for the same code so I don't create duplicate content

**Comment by sargon** [comment]
My opinion on this is that we should carefully check if the puppet script is raising all the services on first apply. For everything else we have monitoring systems, that is what they do. 

When we have anything which is not nicely monitor-able, create a new check for that.

**Comment by rubo77** [comment]
@sargon: But even you do a lot of stuff on the console like

    pgrep fastd

It would be nice to have such a collection of commands how to check the **healt status** of a gateway from within.

**Comment by sargon** [comment]
Yes, of course I do. We have nagios or zabbix for that task, so create checks for everything you find no check for. For prevention of code duplication call these checks.

So a wrapper script around nagios/zabbix checks would be the way to go.

**Comment by rubo77** [comment]
Where can I find the existing checks? (I have no access to the nagios VM)

**Comment by sargon** [comment]
With nagios all checks targeting local status are on the machine, located in ``/etc/nagios/``

**Comment by rubo77** [comment]
OK, so there is nrpe installed on all VPNs that allows the nagios instance on our main server to call the scripts located in /etc/nagios/

This would call them locally: 

    /usr/lib/nagios/plugins/check_nrpe -H localhost

**Comment by rubo77** [comment]
without nagios you can check already some tasks if they are running with these lines:

    service --status-all 2>&1 | egrep '(bird6|openvpn|fastd|alfred|bat)'
    pgrep -lf '(bird6|openvpn|fastd|alfred|bat)'

**Comment by rubo77** [comment]
This would be a script to call on the machine:

https://github.com/ffnord/ffnord-puppet-gateway/pulls?q=is%3Aopen+is%3Apr
